version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: piohhmy/weatherhunt-primary:0.0.1
    steps:
      - checkout
      - run: pip install -r requirements-dev.txt
      - run:
          name: Unit Test
          command: nosetests
          working_directory: ~/ci/nws
      - run: npm install
      - deploy:
          name: Serverless Deploy
          working_directory: ~/ci/nws
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               npm run deploy-prod
            else
               npm run deploy-test
            fi
