version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install -r requirements-dev.txt
      - run:
          name: Unit Test
          command: nosetests
          working_directory: ~/ci/nws
